<a href="https://colab.research.google.com/github/brahmanbhavika06-sketch/my-colab-code/blob/main/session_29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
from google.colab import files

uploaded = files.upload()

Saving train.txt to train (1).txt

In [4]:
import pandas as pd

# Load train.txt
df = pd.read_csv(
    "train.txt",
    sep=";",
    header=None,
    names=["text", "emotion"]
)

print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nFirst 5 Rows:")
display(df.head())

Dataset Shape: (16000, 2)

Column Names:
Index(['text', 'emotion'], dtype='object')

First 5 Rows:

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [5]:
import pandas as pd

# Load train.txt
df = pd.read_csv(
    "train.txt",
    sep=";",
    header=None,
    names=["text", "emotion"]
)

print("Dataset Shape:", df.shape)
print(df.head())

Dataset Shape: (16000, 2)
                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [6]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# Apply cleaning
df["cleaned_text"] = df["text"].apply(clean_text)

print(df[["text", "cleaned_text", "emotion"]].head())

                                                text  \
0                            i didnt feel humiliated
1  i can go from feeling so hopeless to so damned...
2   im grabbing a minute to post i feel greedy wrong
3  i am ever feeling nostalgic about the fireplac...
4                               i am feeling grouchy

                                        cleaned_text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [7]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = df["cleaned_text"]
y = df["emotion"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# Print shapes
print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)
print("y_train Shape:", y_train.shape)
print("y_test Shape:", y_test.shape)

X_train Shape: (12800,)
X_test Shape: (3200,)
y_train Shape: (12800,)
y_test Shape: (3200,)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

# Create CountVectorizer
bow_vectorizer = CountVectorizer()

# Fit and transform training data
X_train_bow = bow_vectorizer.fit_transform(X_train)

# Transform test data
X_test_bow = bow_vectorizer.transform(X_test)

# Print shapes
print("X_train_BOW Shape:", X_train_bow.shape)
print("X_test_BOW Shape:", X_test_bow.shape)

# Display first 20 feature names
print("\nFirst 20 Feature Names:")
print(bow_vectorizer.get_feature_names_out()[:20])

X_train_BOW Shape: (12800, 13501)
X_test_BOW Shape: (3200, 13501)

First 20 Feature Names:
['aa' 'aaaaand' 'aaaand' 'aac' 'aahhh' 'aaron' 'ab' 'abandon' 'abandoned'
 'abandoning' 'abandonment' 'abated' 'abbigail' 'abc' 'abdomen'
 'abdominal' 'abducted' 'abhorrent' 'abide' 'abilities']

In [9]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Create model
nb_bow = MultinomialNB()

# Train model
nb_bow.fit(X_train_bow, y_train)

# Make predictions
y_pred_bow = nb_bow.predict(X_test_bow)

# Calculate accuracy
accuracy_bow = accuracy_score(y_test, y_pred_bow)

print("Bag of Words Accuracy:", accuracy_bow)
print("Bag of Words Accuracy (%):", accuracy_bow * 100)

Bag of Words Accuracy: 0.7390625
Bag of Words Accuracy (%): 73.90625

In [10]:
# Total vocabulary size
print("Total Vocabulary Size:", len(bow_vectorizer.vocabulary_))

# Show 15 vocabulary words
print("\n15 Vocabulary Words:")
print(list(bow_vectorizer.vocabulary_.keys())[:15])

# Select one sample document
sample_document = X_train.iloc[0]

print("\nSample Document:")
print(sample_document)

# Convert sample document into BoW vector
sample_vector = bow_vectorizer.transform([sample_document])

print("\nBoW Vector:")
print(sample_vector.toarray())

Total Vocabulary Size: 13501

15 Vocabulary Words:
['refers', 'of', 'course', 'though', 'cant', 'help', 'feeling', 'somehow', 'ironically', 'in', 'retrospect', 'to', 'loudons', 'son', 'with']

Sample Document:
i refers of course though i cant help feeling somehow ironically in retrospect to loudons son with kate mcgarrigle the rather talented himself rufus wainwright

BoW Vector:
[[0 0 0 ... 0 0 0]]

In [11]:
# Create CountVectorizer with unigrams and bigrams
bigram_vectorizer = CountVectorizer(
    ngram_range=(1, 2)
)

# Fit and transform training data
X_train_bigram = bigram_vectorizer.fit_transform(X_train)

# Transform test data
X_test_bigram = bigram_vectorizer.transform(X_test)

# Print shapes
print("X_train Bigram Shape:", X_train_bigram.shape)
print("X_test Bigram Shape:", X_test_bigram.shape)

# Display some features
print("\nSome Unigram and Bigram Features:")
print(bigram_vectorizer.get_feature_names_out()[:30])

X_train Bigram Shape: (12800, 106150)
X_test Bigram Shape: (3200, 106150)

Some Unigram and Bigram Features:
['aa' 'aa full' 'aa meeting' 'aaaaand' 'aaaaand tis' 'aaaand'
 'aaaand after' 'aac' 'aac or' 'aahhh' 'aahhh work' 'aaron' 'aaron has'
 'ab' 'abandon' 'abandon it' 'abandon me' 'abandon the' 'abandoned'
 'abandoned ask' 'abandoned believe' 'abandoned by' 'abandoning'
 'abandoning him' 'abandonment' 'abandonment has' 'abandonment to'
 'abated' 'abated and' 'abbigail']

In [12]:
# Create Multinomial Naive Bayes model
nb_bigram = MultinomialNB()

# Train model
nb_bigram.fit(X_train_bigram, y_train)

# Make predictions
y_pred_bigram = nb_bigram.predict(X_test_bigram)

# Calculate accuracy
accuracy_bigram = accuracy_score(y_test, y_pred_bigram)

print("Bigram Accuracy:", accuracy_bigram)
print("Bigram Accuracy (%):", accuracy_bigram * 100)

print("\nComparison:")
print("Unigram BoW Accuracy (%):", accuracy_bow * 100)
print("Unigram + Bigram Accuracy (%):", accuracy_bigram * 100)

Bigram Accuracy: 0.6496875
Bigram Accuracy (%): 64.96875

Comparison:
Unigram BoW Accuracy (%): 73.90625
Unigram + Bigram Accuracy (%): 64.96875

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform training data
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

# Transform test data
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Print shapes
print("X_train TF-IDF Shape:", X_train_tfidf.shape)
print("X_test TF-IDF Shape:", X_test_tfidf.shape)

# Display first 15 feature names
print("\nFirst 15 TF-IDF Feature Names:")
print(tfidf_vectorizer.get_feature_names_out()[:15])

X_train TF-IDF Shape: (12800, 13501)
X_test TF-IDF Shape: (3200, 13501)

First 15 TF-IDF Feature Names:
['aa' 'aaaaand' 'aaaand' 'aac' 'aahhh' 'aaron' 'ab' 'abandon' 'abandoned'
 'abandoning' 'abandonment' 'abated' 'abbigail' 'abc' 'abdomen']

In [14]:
# Create Multinomial Naive Bayes model
nb_tfidf = MultinomialNB()

# Train model
nb_tfidf.fit(X_train_tfidf, y_train)

# Make predictions
y_pred_tfidf = nb_tfidf.predict(X_test_tfidf)

# Calculate accuracy
accuracy_tfidf = accuracy_score(y_test, y_pred_tfidf)

print("TF-IDF Accuracy:", accuracy_tfidf)
print("TF-IDF Accuracy (%):", accuracy_tfidf * 100)

TF-IDF Accuracy: 0.6175
TF-IDF Accuracy (%): 61.75000000000001

In [17]:
comparison = pd.DataFrame({
    "Method": [
        "Bag of Words (Unigrams)",
        "Bag of Words (Unigrams + Bigrams)",
        "TF-IDF"
    ],

    "Accuracy": [
        accuracy_bow,
        accuracy_bigram,
        accuracy_tfidf
    ],

    "Accuracy (%)": [
        accuracy_bow * 100,
        accuracy_bigram * 100,
        accuracy_tfidf * 100
    ]
})

display(comparison)

best_index = comparison["Accuracy"].idxmax()

print("Best Method:", comparison.loc[best_index, "Method"])
print("Best Accuracy (%):", comparison.loc[best_index, "Accuracy (%)"])

                              Method  Accuracy  Accuracy (%)
0            Bag of Words (Unigrams)  0.739062      73.90625
1  Bag of Words (Unigrams + Bigrams)  0.649687      64.96875
2                             TF-IDF  0.617500      61.75000

Best Method: Bag of Words (Unigrams)
Best Accuracy (%): 73.90625

In [21]:
import joblib

# Store accuracies
results = {
    "Bag of Words": accuracy_bow,
    "Bag of Words + Bigrams": accuracy_bigram,
    "TF-IDF": accuracy_tfidf
}

# Find best method
best_method = max(results, key=results.get)
best_accuracy = results[best_method]

print("Best Method:", best_method)
print("Best Accuracy:", best_accuracy)
print("Best Accuracy (%):", best_accuracy * 100)

Best Method: Bag of Words
Best Accuracy: 0.7390625
Best Accuracy (%): 73.90625

In [22]:
if best_method == "Bag of Words":
    best_model = nb_bow
    best_vectorizer = bow_vectorizer

elif best_method == "Bag of Words + Bigrams":
    best_model = nb_bigram
    best_vectorizer = bigram_vectorizer

else:
    best_model = nb_tfidf
    best_vectorizer = tfidf_vectorizer

# Save best model
joblib.dump(best_model, "best_emotion_model.pkl")

# Save best vectorizer
joblib.dump(best_vectorizer, "best_emotion_vectorizer.pkl")

print("Best model saved successfully!")
print("Best vectorizer saved successfully!")

Best model saved successfully!
Best vectorizer saved successfully!

In [23]:
import os

print(os.listdir())

['.config', 'best_emotion_model.pkl', 'train.txt', 'best_emotion_vectorizer.pkl', 'sample_data']